version: '3'
services:
  minecraft:
    image: itzg/minecraft-server:latest
    container_name: minecraft
    ports: 
      - "25565:25565"
    volumes:
      - ./mc_data:/data
    environment:
      EULA: 'TRUE'
